project:
  type: website
  output-dir: _site

website:
  title: "Drew Ralston"                    # <-- CHANGE THIS
  description: "Computer Science Engineering Student at Ohio State University" # <-- CHANGE THIS
  site-url: https://dralston168.github.io  # <-- CHANGE THIS

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/dralston168  # <-- CHANGE THIS
      - icon: envelope
        href: mailto:ralston.168@osu.edu  # <-- CHANGE THIS

  page-footer:
    center: |
      Built with [Quarto](https://quarto.org/) · © 2025 Drew Ralston

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

execute:
  freeze: auto
